# Generated by Django 5.0 on 2025-12-21 19:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("ACCESS", "Access"),
                        ],
                        db_index=True,
                        max_length=100,
                    ),
                ),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                ("object_id", models.UUIDField(blank=True, null=True)),
                (
                    "changes",
                    models.JSONField(
                        blank=True, help_text="JSON of old and new values", null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.CharField(max_length=500)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_logs_user_id_88267f_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="audit_logs_action_474804_idx",
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="audit_logs_model_n_656046_idx",
                    ),
                ],
            },
        ),
    ]
