# Generated by Django 5.0 on 2025-12-21 19:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "course_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("course_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "credits",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("department", models.CharField(db_index=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True, related_name="required_for", to="courses.course"
                    ),
                ),
            ],
            options={
                "db_table": "courses",
                "ordering": ["course_code"],
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "class_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("section", models.CharField(max_length=10)),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("FALL", "Fall"),
                            ("SPRING", "Spring"),
                            ("SUMMER", "Summer"),
                        ],
                        max_length=10,
                    ),
                ),
                ("academic_year", models.IntegerField()),
                (
                    "max_capacity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("current_enrollment", models.IntegerField(default=0)),
                (
                    "schedule",
                    models.JSONField(
                        default=list, help_text="Array of {day, start_time, end_time}"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        limit_choices_to={"role": "INSTRUCTOR"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taught_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Classes",
                "db_table": "classes",
                "ordering": ["-academic_year", "semester", "class_code"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "room_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("building", models.CharField(max_length=100)),
                (
                    "capacity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("CLASSROOM", "Classroom"),
                            ("LAB", "Laboratory"),
                            ("LECTURE_HALL", "Lecture Hall"),
                            ("SEMINAR", "Seminar Room"),
                        ],
                        max_length=20,
                    ),
                ),
                ("equipment", models.JSONField(blank=True, default=list)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rooms",
                "ordering": ["building", "room_number"],
                "indexes": [
                    models.Index(
                        fields=["room_number"], name="rooms_room_nu_5c8eca_idx"
                    ),
                    models.Index(fields=["building"], name="rooms_buildin_5c1aee_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("MIDTERM", "Midterm"),
                            ("FINAL", "Final"),
                            ("QUIZ", "Quiz"),
                            ("PROJECT", "Project"),
                        ],
                        max_length=20,
                    ),
                ),
                ("exam_date", models.DateTimeField()),
                (
                    "duration_minutes",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="courses.class",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exams",
                        to="courses.room",
                    ),
                ),
            ],
            options={
                "db_table": "exams",
                "ordering": ["exam_date"],
            },
        ),
        migrations.AddField(
            model_name="class",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes",
                to="courses.room",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["course_code"], name="courses_course__5da9ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["department"], name="courses_departm_797740_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["class_instance", "exam_type"], name="exams_class_i_34c7ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["exam_date"], name="exams_exam_da_14bdc1_idx"),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["class_code"], name="classes_class_c_7f1d7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["semester", "academic_year"], name="classes_semeste_d84259_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["instructor"], name="classes_instruc_f74f76_idx"
            ),
        ),
    ]
