# Generated by Django 5.0 on 2025-12-22 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_created_e4c995_idx",
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("GRADE", "Grade"),
                    ("ATTENDANCE", "Attendance"),
                    ("ENROLLMENT", "Enrollment"),
                    ("ANNOUNCEMENT", "Announcement"),
                    ("SYSTEM", "System"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="studentrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="studentrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("TRANSCRIPT", "Transcript"),
                    ("CERTIFICATE", "Certificate"),
                    ("COURSE_ADD", "Course Add"),
                    ("COURSE_DROP", "Course Drop"),
                    ("GRADE_APPEAL", "Grade Appeal"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["recipient", "created_at"], name="messages_recipie_684425_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "created_at"],
                name="notificatio_recipie_2c3905_idx",
            ),
        ),
    ]
